name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Check API_KEY
        run: echo "API_KEY=${{ secrets.API_KEY }}"

      - name: Create .env file
        run: |
          mkdir -p assets
          echo "API_KEY=${{ secrets.API_KEY }}" > assets/.env

      - name: Run tests
        run: flutter test

      - name: Build web
        run: flutter build web --release

      - name: Copy .env to build/web
        run: cp assets/.env build/web/assets/.env

      - name: Create 404.html
        run: |
          echo "<!DOCTYPE html><html><head><meta http-equiv=\"refresh\" content=\"0; URL='./index.html'\" /></head></html>" > build/web/404.html

      - name: Update base href
        run: |
          sed -i 's|<base href="/">|<base href="/injection_dependency/">|' build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
